BETA_SIG = 0.2
BETA_PIX = 1.0
CMAP_DEFAULT = 'gray'  # 'viridis'
CMAP_ALTERNATIVE = 'gray'  # 'inferno'
CMAP_OTHER = 'magma'  # 'gray'
DIMA_BORDERS_EXE = './../DimaBorders/release/border.exe'
EPS = 1e-10
MIN_CONTOUR_AREA = 100.0
MIN_CONTOUR_N = 50
MIN_THETA_DIFF = 1e-1
MULT_INIT = 2
NEIB_HULL = 1  # 0.05
NEIB_APPR = 1  # 0.05
TIMEIT_ITERS = 3
Q_MAX_MULT = 1.5
Q_SIGNAL = 30
Q_PIXELS = 25
